version: '3'

services:
  api_severstal_equip:
    image: gitlab.vniizht.lan:5050/ml_projects/api_severstal_equip:latest
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api_severstal_equip
    command: gunicorn app.main:app -k uvicorn.workers.UvicornWorker --log-config=logconf.ini
    environment:
      - ENVIRONMENT=dev
      - TZ=Europe/Moscow
      - DEVICE=cuda:0
      - TOKENIZERS_PARALLELISM=true
    ports:
      - 3020:8000
    restart: always
    volumes:
      - ./app:/opt/app
      - ./gunicorn.conf.py:/opt/gunicorn.conf.py
      - ./.env.dev:/opt/.env.dev
    logging:
      driver: "json-file"
      options:
          max-size: "10m"
          max-file: "10"
    deploy:
      resources:
        limits:
          cpus: '24'
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
