CREATE TABLE IF NOT EXISTS hakaton.predict_m3_exg5
(
    dt      DATETIME,
    oil_cooler_m_05_1 Nullable(UInt32),
    electric_motor_dspu_140_84_4 Nullable(UInt32),
    casing Nullable(UInt32),
    valve Nullable(UInt32),
    support_bearing Nullable(UInt32),
    support_bearing_no_2 Nullable(UInt32),
    thrust_bearing Nullable(UInt32),
    gear_oil_pump_spare Nullable(UInt32),
    vk_310c_vibration_transducer_exhauster_no_5_p_1 Nullable(UInt32),
    vk_310c_vibration_transducer_exhauster_no_5_p_3 Nullable(UInt32),
    electrical_equipment_of_exhauster_no_5 Nullable(UInt32),
    vk_310c_vibration_transducer_exhauster_no_5_p_2 Nullable(UInt32),
    support_bearing_no_1 Nullable(UInt32),
    gas_valve_reducer Nullable(UInt32),
    thyristor_exciter_vt_rem_400_exhauster_no_5_vu1 Nullable(UInt32),
    shutoff_valves_for_exhauster_no_5 Nullable(UInt32),
    oil_pipelines_for_exhauster_no_5 Nullable(UInt32),
    fuel Nullable(UInt32),
    exhauster_vehicle_no_5 Nullable(UInt32),
    tsmc_101_010_50m_80_oil_temperature_transducer Nullable(UInt32),
    tr_r_tm_4000_10_6 Nullable(UInt32),
    cable_gland_1_tr_no_5_to_exhauster_no_5_motor_starter Nullable(UInt32),
    cable_gland_2_tr_no_5_to_exhauster_no_5_motor_starter Nullable(UInt32),
    working_oil_pump Nullable(UInt32),
    rotor Nullable(UInt32),
    metran_100_pressure_sensors_exhauster_no_5 Nullable(UInt32),
    starter_oil_pump_motor Nullable(UInt32),
    gas_valve_for_exhauster_vehicle_no_5 Nullable(UInt32),
    coupling_housing Nullable(UInt32),
    thyistorexcitervt_rem_400exhausterno_5vu2 Nullable(UInt32),
    tsmc_101_010_50m_400supportbearingtemp_transducert_2 Nullable(UInt32),
    backupoilpumpmotorforexhausterno_5 Nullable(UInt32),
    tsmc_101_010_50m_200supportbearingtemp_transducert_3 Nullable(UInt32),
    exhaustern_8000vehicleno_5 Nullable(UInt32),
    equip_with_anomaly Nullable(UInt32)
)
ENGINE = MergeTree
ORDER BY (dt)