CREATE TABLE IF NOT EXISTS hakaton.predict_m3_exg4
(
    dt      DATETIME,
    motor Nullable(UInt32),
    housing Nullable(UInt32),
    support_bearing_1 Nullable(UInt32),
    valve Nullable(UInt32),
    support_bearing_2 Nullable(UInt32),
    rotor Nullable(UInt32),
    thrust_bearing Nullable(UInt32),
    vibroconverter_VK_310S_EXG_7_T3 Nullable(UInt32),
    gas_valve_reducer Nullable(UInt32),
    temperature_sensor_80_3_EXG_7 Nullable(UInt32),
    support_bearing Nullable(UInt32),
    gasoline Nullable(UInt32),
    coupling_cover Nullable(UInt32),
    exhauster_EXG_7 Nullable(UInt32),
    oil_pipes_EXG_7 Nullable(UInt32),
    oil_cooler_M_05_1 Nullable(UInt32),
    sapphire_sensor_22_MDD_cyclone_pressure_drop Nullable(UInt32),
    electrical_equipment_EXG_7 Nullable(UInt32),
    working_oil_pump Nullable(UInt32),
    gear_oil_pump_EXG_7 Nullable(UInt32),
    oil_filter_EXG_7 Nullable(UInt32),
    transformer_TM_4000_10_6 Nullable(UInt32),
    temperature_sensor_200_3_EXG_7 Nullable(UInt32),
    vibroconverter_VK_310S_EXG_7_T2 Nullable(UInt32),
    vibroconverter_VK_310S_EXG_7_T4 Nullable(UInt32),
    thyristor_exciter_TV_400_EXG_7_WU1 Nullable(UInt32),
    temperature_sensor_400_2_EXG_7 Nullable(UInt32),
    CL1_TR_7_to_ED_EXG_7 Nullable(UInt32),
    metran_100_pressure_sensors_EXG_7 Nullable(UInt32),
    regulating_equipment_EXG_7 Nullable(UInt32),
    gas_valve_motor Nullable(UInt32),
    temperature_sensor_400_1_EXG_7 Nullable(UInt32),
    equip_with_anomaly Nullable(UInt32)
)
ENGINE = MergeTree
ORDER BY (dt)